apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
        - name: migrate
          image: arhamajain1/django-dcrm-image:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: django-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: django-configmap
                  key: REDIS_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: django-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: MYSQL_ROOT_PASSWORD
      containers:
        - name: django
          image: arhamajain1/django-dcrm-image:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: django-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: django-configmap
                  key: REDIS_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: django-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: MYSQL_ROOT_PASSWORD
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
